using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DetectiveInterrogation.Migrations
{
    /// <inheritdoc />
    public partial class MoveManualSchemaChangesToMigration : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
CREATE TABLE IF NOT EXISTS "Achievements" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" character varying(255) NOT NULL,
    "Description" text,
    CONSTRAINT "PK_Achievements" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "Cases" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" character varying(255) NOT NULL,
    "NewspaperText" text,
    "ShortDescription" text,
    "FullDescription" text,
    "EndingSuccessText" text,
    "EndingRefusalText" text,
    "EndingDefaultText" text,
    "CourtImagePath" character varying(500),
    "PrisonImagePath" character varying(500),
    CONSTRAINT "PK_Cases" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Username" character varying(50) NOT NULL,
    "Email" character varying(255) NOT NULL,
    "PasswordHash" text NOT NULL,
    "Role" character varying(32) NOT NULL DEFAULT 'Player',
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "Evidence" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CaseId" integer NOT NULL,
    "SuspectId" character varying(20) NOT NULL,
    "Title" character varying(255) NOT NULL,
    "Description" text NOT NULL,
    CONSTRAINT "PK_Evidence" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Evidence_Cases_CaseId" FOREIGN KEY ("CaseId") REFERENCES "Cases" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "Suspects" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CaseId" integer NOT NULL,
    "Name" character varying(255) NOT NULL,
    "Description" text,
    "InitialTrust" integer NOT NULL DEFAULT 50,
    "InitialPressure" integer NOT NULL DEFAULT 50,
    "IsGuilty" boolean NOT NULL,
    CONSTRAINT "PK_Suspects" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Suspects_Cases_CaseId" FOREIGN KEY ("CaseId") REFERENCES "Cases" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "UserAchievements" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "AchievementId" integer NOT NULL,
    CONSTRAINT "PK_UserAchievements" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserAchievements_Achievements_AchievementId" FOREIGN KEY ("AchievementId") REFERENCES "Achievements" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_UserAchievements_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "EvidencePhrases" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "EvidenceId" integer NOT NULL,
    "Text" text NOT NULL,
    "TrustChange" integer NOT NULL DEFAULT 0,
    "PressureChange" integer NOT NULL DEFAULT 0,
    CONSTRAINT "PK_EvidencePhrases" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_EvidencePhrases_Evidence_EvidenceId" FOREIGN KEY ("EvidenceId") REFERENCES "Evidence" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "InterrogationSessions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CaseId" integer NOT NULL,
    "SuspectId" integer NOT NULL,
    "UserId" integer NOT NULL,
    "CurrentTrust" integer NOT NULL DEFAULT 50,
    "CurrentPressure" integer NOT NULL DEFAULT 50,
    "Status" character varying(20) NOT NULL DEFAULT 'InProgress',
    CONSTRAINT "PK_InterrogationSessions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_InterrogationSessions_Cases_CaseId" FOREIGN KEY ("CaseId") REFERENCES "Cases" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_InterrogationSessions_Suspects_SuspectId" FOREIGN KEY ("SuspectId") REFERENCES "Suspects" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_InterrogationSessions_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "SuspectReplies" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "SuspectId" integer NOT NULL,
    "EvidencePhraseId" integer NOT NULL,
    "MinTrust" integer NOT NULL,
    "MaxTrust" integer NOT NULL,
    "MinPressure" integer NOT NULL,
    "MaxPressure" integer NOT NULL,
    "Text" text NOT NULL,
    CONSTRAINT "PK_SuspectReplies" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SuspectReplies_EvidencePhrases_EvidencePhraseId" FOREIGN KEY ("EvidencePhraseId") REFERENCES "EvidencePhrases" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_SuspectReplies_Suspects_SuspectId" FOREIGN KEY ("SuspectId") REFERENCES "Suspects" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "SessionUsedEvidences" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "EvidenceId" integer NOT NULL,
    "SessionId" integer NOT NULL,
    CONSTRAINT "PK_SessionUsedEvidences" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SessionUsedEvidences_Evidence_EvidenceId" FOREIGN KEY ("EvidenceId") REFERENCES "Evidence" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_SessionUsedEvidences_InterrogationSessions_SessionId" FOREIGN KEY ("SessionId") REFERENCES "InterrogationSessions" ("Id") ON DELETE CASCADE
);

DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'Suspects' AND column_name = 'InitialAggression'
    ) AND NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'Suspects' AND column_name = 'InitialPressure'
    ) THEN
        ALTER TABLE "Suspects" RENAME COLUMN "InitialAggression" TO "InitialPressure";
    END IF;

    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'InterrogationSessions' AND column_name = 'CurrentAggression'
    ) AND NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'InterrogationSessions' AND column_name = 'CurrentPressure'
    ) THEN
        ALTER TABLE "InterrogationSessions" RENAME COLUMN "CurrentAggression" TO "CurrentPressure";
    END IF;

    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'SuspectReplies' AND column_name = 'PhraseId'
    ) AND NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'SuspectReplies' AND column_name = 'EvidencePhraseId'
    ) THEN
        ALTER TABLE "SuspectReplies" RENAME COLUMN "PhraseId" TO "EvidencePhraseId";
    END IF;

    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'SuspectReplies' AND column_name = 'ReplyText'
    ) AND NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'SuspectReplies' AND column_name = 'Text'
    ) THEN
        ALTER TABLE "SuspectReplies" RENAME COLUMN "ReplyText" TO "Text";
    END IF;
END $$;

ALTER TABLE "Cases" ADD COLUMN IF NOT EXISTS "EndingSuccessText" text;
ALTER TABLE "Cases" ADD COLUMN IF NOT EXISTS "EndingRefusalText" text;
ALTER TABLE "Cases" ADD COLUMN IF NOT EXISTS "EndingDefaultText" text;
ALTER TABLE "Cases" ADD COLUMN IF NOT EXISTS "CourtImagePath" character varying(500);
ALTER TABLE "Cases" ADD COLUMN IF NOT EXISTS "PrisonImagePath" character varying(500);

ALTER TABLE "Suspects" DROP COLUMN IF EXISTS "InitialAggression";
ALTER TABLE "InterrogationSessions" DROP COLUMN IF EXISTS "CurrentAggression";

ALTER TABLE "Evidence" ADD COLUMN IF NOT EXISTS "SuspectId" character varying(20) NOT NULL DEFAULT '';
ALTER TABLE "Evidence" ADD COLUMN IF NOT EXISTS "Description" text NOT NULL DEFAULT '';
ALTER TABLE "Evidence" DROP COLUMN IF EXISTS "ShortText";
ALTER TABLE "Evidence" DROP COLUMN IF EXISTS "FullText";

ALTER TABLE "EvidencePhrases" ADD COLUMN IF NOT EXISTS "TrustChange" integer NOT NULL DEFAULT 0;
ALTER TABLE "EvidencePhrases" ADD COLUMN IF NOT EXISTS "PressureChange" integer NOT NULL DEFAULT 0;

ALTER TABLE "SuspectReplies" ADD COLUMN IF NOT EXISTS "EvidencePhraseId" integer NOT NULL DEFAULT 0;
ALTER TABLE "SuspectReplies" ADD COLUMN IF NOT EXISTS "MinTrust" integer NOT NULL DEFAULT 0;
ALTER TABLE "SuspectReplies" ADD COLUMN IF NOT EXISTS "MaxTrust" integer NOT NULL DEFAULT 100;
ALTER TABLE "SuspectReplies" ADD COLUMN IF NOT EXISTS "MinPressure" integer NOT NULL DEFAULT 0;
ALTER TABLE "SuspectReplies" ADD COLUMN IF NOT EXISTS "MaxPressure" integer NOT NULL DEFAULT 100;
ALTER TABLE "SuspectReplies" ADD COLUMN IF NOT EXISTS "Text" text NOT NULL DEFAULT '';
ALTER TABLE "SuspectReplies" DROP COLUMN IF EXISTS "PhraseId";
ALTER TABLE "SuspectReplies" DROP COLUMN IF EXISTS "ReplyText";
ALTER TABLE "SuspectReplies" DROP COLUMN IF EXISTS "TrustChange";
ALTER TABLE "SuspectReplies" DROP COLUMN IF EXISTS "AggressionChange";

CREATE INDEX IF NOT EXISTS "IX_Evidence_CaseId" ON "Evidence" ("CaseId");
CREATE INDEX IF NOT EXISTS "IX_EvidencePhrases_EvidenceId" ON "EvidencePhrases" ("EvidenceId");
CREATE INDEX IF NOT EXISTS "IX_InterrogationSessions_CaseId" ON "InterrogationSessions" ("CaseId");
CREATE INDEX IF NOT EXISTS "IX_InterrogationSessions_SuspectId" ON "InterrogationSessions" ("SuspectId");
CREATE INDEX IF NOT EXISTS "IX_InterrogationSessions_UserId" ON "InterrogationSessions" ("UserId");
CREATE INDEX IF NOT EXISTS "IX_SessionUsedEvidences_EvidenceId" ON "SessionUsedEvidences" ("EvidenceId");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_SessionUsedEvidences_SessionId_EvidenceId" ON "SessionUsedEvidences" ("SessionId", "EvidenceId");
CREATE INDEX IF NOT EXISTS "IX_SuspectReplies_EvidencePhraseId" ON "SuspectReplies" ("EvidencePhraseId");
CREATE INDEX IF NOT EXISTS "IX_SuspectReplies_SuspectId" ON "SuspectReplies" ("SuspectId");
CREATE INDEX IF NOT EXISTS "IX_Suspects_CaseId" ON "Suspects" ("CaseId");
CREATE INDEX IF NOT EXISTS "IX_UserAchievements_AchievementId" ON "UserAchievements" ("AchievementId");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_UserAchievements_UserId_AchievementId" ON "UserAchievements" ("UserId", "AchievementId");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Users_Email" ON "Users" ("Email");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Users_Username" ON "Users" ("Username");
""");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
DROP TABLE IF EXISTS "SessionUsedEvidences";
DROP TABLE IF EXISTS "SuspectReplies";
DROP TABLE IF EXISTS "UserAchievements";
DROP TABLE IF EXISTS "InterrogationSessions";
DROP TABLE IF EXISTS "EvidencePhrases";
DROP TABLE IF EXISTS "Achievements";
DROP TABLE IF EXISTS "Suspects";
DROP TABLE IF EXISTS "Users";
DROP TABLE IF EXISTS "Evidence";
DROP TABLE IF EXISTS "Cases";
""");
        }
    }
}
