// <auto-generated />
using DetectiveInterrogation.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DetectiveInterrogation.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260508101727_MoveManualSchemaChangesToMigration")]
    partial class MoveManualSchemaChangesToMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DetectiveInterrogation.Models.Entities.Achievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("Achievements");
                });

            modelBuilder.Entity("DetectiveInterrogation.Models.Entities.Case", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CourtImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("EndingDefaultText")
                        .HasColumnType("text");

                    b.Property<string>("EndingRefusalText")
                        .HasColumnType("text");

                    b.Property<string>("EndingSuccessText")
                        .HasColumnType("text");

                    b.Property<string>("FullDescription")
                        .HasColumnType("text");

                    b.Property<string>("NewspaperText")
                        .HasColumnType("text");

                    b.Property<string>("PrisonImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("Cases");
                });

            modelBuilder.Entity("DetectiveInterrogation.Models.Entities.Evidence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CaseId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SuspectId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.ToTable("Evidence");
                });

            modelBuilder.Entity("DetectiveInterrogation.Models.Entities.EvidencePhrase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EvidenceId")
                        .HasColumnType("integer");

                    b.Property<int>("PressureChange")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TrustChange")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("EvidenceId");

                    b.ToTable("EvidencePhrases");
                });

            modelBuilder.Entity("DetectiveInterrogation.Models.Entities.InterrogationSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CaseId")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentPressure")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(50);

                    b.Property<int>("CurrentTrust")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(50);

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("InProgress");

                    b.Property<int>("SuspectId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.HasIndex("SuspectId");

                    b.HasIndex("UserId");

                    b.ToTable("InterrogationSessions");
                });

            modelBuilder.Entity("DetectiveInterrogation.Models.Entities.SessionUsedEvidence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EvidenceId")
                        .HasColumnType("integer");

                    b.Property<int>("SessionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EvidenceId");

                    b.HasIndex("SessionId", "EvidenceId")
                        .IsUnique();

                    b.ToTable("SessionUsedEvidences");
                });

            modelBuilder.Entity("DetectiveInterrogation.Models.Entities.Suspect", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CaseId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("InitialPressure")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(50);

                    b.Property<int>("InitialTrust")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(50);

                    b.Property<bool>("IsGuilty")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.ToTable("Suspects");
                });

            modelBuilder.Entity("DetectiveInterrogation.Models.Entities.SuspectReply", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EvidencePhraseId")
                        .HasColumnType("integer");

                    b.Property<int>("MaxPressure")
                        .HasColumnType("integer");

                    b.Property<int>("MaxTrust")
                        .HasColumnType("integer");

                    b.Property<int>("MinPressure")
                        .HasColumnType("integer");

                    b.Property<int>("MinTrust")
                        .HasColumnType("integer");

                    b.Property<int>("SuspectId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EvidencePhraseId");

                    b.HasIndex("SuspectId");

                    b.ToTable("SuspectReplies");
                });

            modelBuilder.Entity("DetectiveInterrogation.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("Player");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DetectiveInterrogation.Models.Entities.UserAchievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AchievementId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AchievementId");

                    b.HasIndex("UserId", "AchievementId")
                        .IsUnique();

                    b.ToTable("UserAchievements");
                });

            modelBuilder.Entity("DetectiveInterrogation.Models.Entities.Evidence", b =>
                {
                    b.HasOne("DetectiveInterrogation.Models.Entities.Case", "Case")
                        .WithMany("Evidence")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("DetectiveInterrogation.Models.Entities.EvidencePhrase", b =>
                {
                    b.HasOne("DetectiveInterrogation.Models.Entities.Evidence", "Evidence")
                        .WithMany("Phrases")
                        .HasForeignKey("EvidenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evidence");
                });

            modelBuilder.Entity("DetectiveInterrogation.Models.Entities.InterrogationSession", b =>
                {
                    b.HasOne("DetectiveInterrogation.Models.Entities.Case", "Case")
                        .WithMany("InterrogationSessions")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DetectiveInterrogation.Models.Entities.Suspect", "Suspect")
                        .WithMany("InterrogationSessions")
                        .HasForeignKey("SuspectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DetectiveInterrogation.Models.Entities.User", "User")
                        .WithMany("InterrogationSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");

                    b.Navigation("Suspect");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DetectiveInterrogation.Models.Entities.SessionUsedEvidence", b =>
                {
                    b.HasOne("DetectiveInterrogation.Models.Entities.Evidence", "Evidence")
                        .WithMany("SessionUsedEvidences")
                        .HasForeignKey("EvidenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DetectiveInterrogation.Models.Entities.InterrogationSession", "Session")
                        .WithMany("SessionUsedEvidences")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evidence");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("DetectiveInterrogation.Models.Entities.Suspect", b =>
                {
                    b.HasOne("DetectiveInterrogation.Models.Entities.Case", "Case")
                        .WithMany("Suspects")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("DetectiveInterrogation.Models.Entities.SuspectReply", b =>
                {
                    b.HasOne("DetectiveInterrogation.Models.Entities.EvidencePhrase", "Phrase")
                        .WithMany("SuspectReplies")
                        .HasForeignKey("EvidencePhraseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DetectiveInterrogation.Models.Entities.Suspect", "Suspect")
                        .WithMany("Replies")
                        .HasForeignKey("SuspectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phrase");

                    b.Navigation("Suspect");
                });

            modelBuilder.Entity("DetectiveInterrogation.Models.Entities.UserAchievement", b =>
                {
                    b.HasOne("DetectiveInterrogation.Models.Entities.Achievement", "Achievement")
                        .WithMany("UserAchievements")
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DetectiveInterrogation.Models.Entities.User", "User")
                        .WithMany("UserAchievements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achievement");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DetectiveInterrogation.Models.Entities.Achievement", b =>
                {
                    b.Navigation("UserAchievements");
                });

            modelBuilder.Entity("DetectiveInterrogation.Models.Entities.Case", b =>
                {
                    b.Navigation("Evidence");

                    b.Navigation("InterrogationSessions");

                    b.Navigation("Suspects");
                });

            modelBuilder.Entity("DetectiveInterrogation.Models.Entities.Evidence", b =>
                {
                    b.Navigation("Phrases");

                    b.Navigation("SessionUsedEvidences");
                });

            modelBuilder.Entity("DetectiveInterrogation.Models.Entities.EvidencePhrase", b =>
                {
                    b.Navigation("SuspectReplies");
                });

            modelBuilder.Entity("DetectiveInterrogation.Models.Entities.InterrogationSession", b =>
                {
                    b.Navigation("SessionUsedEvidences");
                });

            modelBuilder.Entity("DetectiveInterrogation.Models.Entities.Suspect", b =>
                {
                    b.Navigation("InterrogationSessions");

                    b.Navigation("Replies");
                });

            modelBuilder.Entity("DetectiveInterrogation.Models.Entities.User", b =>
                {
                    b.Navigation("InterrogationSessions");

                    b.Navigation("UserAchievements");
                });
#pragma warning restore 612, 618
        }
    }
}
